apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
    namespace: webapp
type: Opaque
data:
    mongo-root-username: Umlkd2Fu
    mongo-root-password: UGFzc3dvcmQ=
